# Generated by skir-elixir-gen 0.3.0. DO NOT EDIT.
# Source: tree.skir

defmodule Example.Protocol.TreeSkir.Loop do
  @moduledoc "Generated from tree.skir:Loop"
  defstruct [{:next, :skir_default}, {:__skir_unknown_fields__, %{}}]
  @type t :: %__MODULE__{:next => (Example.Protocol.TreeSkir.Loop.t() | :skir_default), :__skir_unknown_fields__ => map()}
  @spec new(map() | keyword()) :: t()
  def new(attrs \\ %{}), do: struct!(__MODULE__, attrs)
  @spec default() :: t()
  def default(), do: %__MODULE__{}
  @doc false
  def schema() do
    %{kind: :struct, module: __MODULE__, key: "tree.skir:Loop", doc: "",
      slots: 1, removed: [],
      fields: [%{name: :next, json_name: "next", number: 0, doc: "", type: {:record, Example.Protocol.TreeSkir.Loop}, key_path: []}]}
  end
  @spec type() :: Skir.type()
  def type(), do: {:record, __MODULE__}
  @spec to_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def to_json(value, opts \\ []), do: Skir.to_json(type(), value, opts)
  @spec to_json!(term(), keyword()) :: term()
  def to_json!(value, opts \\ []), do: Skir.to_json!(type(), value, opts)
  @spec from_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def from_json(value, opts \\ []), do: Skir.from_json(type(), value, opts)
  @spec from_json!(term(), keyword()) :: term()
  def from_json!(value, opts \\ []), do: Skir.from_json!(type(), value, opts)
  @spec encode_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def encode_json(value, opts \\ []), do: Skir.encode_json(type(), value, opts)
  @spec encode_json!(term(), keyword()) :: binary()
  def encode_json!(value, opts \\ []), do: Skir.encode_json!(type(), value, opts)
  @spec decode_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def decode_json(value, opts \\ []), do: Skir.decode_json(type(), value, opts)
  @spec decode_json!(term(), keyword()) :: term()
  def decode_json!(value, opts \\ []), do: Skir.decode_json!(type(), value, opts)
  @spec encode(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def encode(value, opts \\ []), do: Skir.encode(type(), value, opts)
  @spec encode!(term(), keyword()) :: binary()
  def encode!(value, opts \\ []), do: Skir.encode!(type(), value, opts)
  @spec decode(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def decode(value, opts \\ []), do: Skir.decode(type(), value, opts)
  @spec decode!(term(), keyword()) :: term()
  def decode!(value, opts \\ []), do: Skir.decode!(type(), value, opts)
end

defmodule Example.Protocol.TreeSkir.Node do
  @moduledoc "Generated from tree.skir:Node"
  defstruct [{:value, ""}, {:next, nil}, {:children, []}, {:__skir_unknown_fields__, %{}}]
  @type t :: %__MODULE__{:value => (String.t()), :next => (nil | Example.Protocol.TreeSkir.Node.t() | :skir_default), :children => ([Example.Protocol.TreeSkir.Node.t() | :skir_default]), :__skir_unknown_fields__ => map()}
  @spec new(map() | keyword()) :: t()
  def new(attrs \\ %{}), do: struct!(__MODULE__, attrs)
  @spec default() :: t()
  def default(), do: %__MODULE__{}
  @doc false
  def schema() do
    %{kind: :struct, module: __MODULE__, key: "tree.skir:Node", doc: "",
      slots: 3, removed: [],
      fields: [%{name: :value, json_name: "value", number: 0, doc: "", type: :string, key_path: []},
        %{name: :next, json_name: "next", number: 1, doc: "", type: {:optional, {:record, Example.Protocol.TreeSkir.Node}}, key_path: []},
        %{name: :children, json_name: "children", number: 2, doc: "", type: {:array, {:record, Example.Protocol.TreeSkir.Node}}, key_path: []}]}
  end
  @spec type() :: Skir.type()
  def type(), do: {:record, __MODULE__}
  @spec to_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def to_json(value, opts \\ []), do: Skir.to_json(type(), value, opts)
  @spec to_json!(term(), keyword()) :: term()
  def to_json!(value, opts \\ []), do: Skir.to_json!(type(), value, opts)
  @spec from_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def from_json(value, opts \\ []), do: Skir.from_json(type(), value, opts)
  @spec from_json!(term(), keyword()) :: term()
  def from_json!(value, opts \\ []), do: Skir.from_json!(type(), value, opts)
  @spec encode_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def encode_json(value, opts \\ []), do: Skir.encode_json(type(), value, opts)
  @spec encode_json!(term(), keyword()) :: binary()
  def encode_json!(value, opts \\ []), do: Skir.encode_json!(type(), value, opts)
  @spec decode_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def decode_json(value, opts \\ []), do: Skir.decode_json(type(), value, opts)
  @spec decode_json!(term(), keyword()) :: term()
  def decode_json!(value, opts \\ []), do: Skir.decode_json!(type(), value, opts)
  @spec encode(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def encode(value, opts \\ []), do: Skir.encode(type(), value, opts)
  @spec encode!(term(), keyword()) :: binary()
  def encode!(value, opts \\ []), do: Skir.encode!(type(), value, opts)
  @spec decode(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def decode(value, opts \\ []), do: Skir.decode(type(), value, opts)
  @spec decode!(term(), keyword()) :: term()
  def decode!(value, opts \\ []), do: Skir.decode!(type(), value, opts)
end

defmodule Example.Protocol.TreeSkir do
  @moduledoc "Constants and method descriptors for this Skir source file."
end
