# Generated by skir-elixir-gen 0.3.0. DO NOT EDIT.
# Source: user.skir

defmodule Example.Protocol.UserSkir.Event do
  @moduledoc "Generated from user.skir:Event"
  @type t :: :unknown | {:unknown, Skir.Unknown.t()} | :connected | {:user_created, (Example.Protocol.UserSkir.User.t() | :skir_default)} | {:message, (String.t())}
  @spec default() :: t()
  def default(), do: :unknown
  @doc false
  def schema() do
    %{kind: :enum, module: __MODULE__, key: "user.skir:Event", doc: "",
      slots: 0, removed: [3, 4],
      fields: [%{name: :connected, json_name: "connected", number: 1, doc: "", type: nil, key_path: []},
        %{name: :user_created, json_name: "user_created", number: 2, doc: "", type: {:record, Example.Protocol.UserSkir.User}, key_path: []},
        %{name: :message, json_name: "message", number: 5, doc: "", type: :string, key_path: []}]}
  end
  @spec type() :: Skir.type()
  def type(), do: {:record, __MODULE__}
  @spec to_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def to_json(value, opts \\ []), do: Skir.to_json(type(), value, opts)
  @spec to_json!(term(), keyword()) :: term()
  def to_json!(value, opts \\ []), do: Skir.to_json!(type(), value, opts)
  @spec from_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def from_json(value, opts \\ []), do: Skir.from_json(type(), value, opts)
  @spec from_json!(term(), keyword()) :: term()
  def from_json!(value, opts \\ []), do: Skir.from_json!(type(), value, opts)
  @spec encode_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def encode_json(value, opts \\ []), do: Skir.encode_json(type(), value, opts)
  @spec encode_json!(term(), keyword()) :: binary()
  def encode_json!(value, opts \\ []), do: Skir.encode_json!(type(), value, opts)
  @spec decode_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def decode_json(value, opts \\ []), do: Skir.decode_json(type(), value, opts)
  @spec decode_json!(term(), keyword()) :: term()
  def decode_json!(value, opts \\ []), do: Skir.decode_json!(type(), value, opts)
  @spec encode(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def encode(value, opts \\ []), do: Skir.encode(type(), value, opts)
  @spec encode!(term(), keyword()) :: binary()
  def encode!(value, opts \\ []), do: Skir.encode!(type(), value, opts)
  @spec decode(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def decode(value, opts \\ []), do: Skir.decode(type(), value, opts)
  @spec decode!(term(), keyword()) :: term()
  def decode!(value, opts \\ []), do: Skir.decode!(type(), value, opts)
end

defmodule Example.Protocol.UserSkir.User do
  @moduledoc "Generated from user.skir:User"
  defstruct [{:id, 0}, {:name, ""}, {:active, false}, {:nickname, nil}, {:pets, []}, {:address, %{:__struct__ => Example.Protocol.CommonSkir.Address, :city => "", :__skir_unknown_fields__ => %{}}}, {:avatar, <<>>}, {:created_at, 0}, {:status, :unknown}, {:__skir_unknown_fields__, %{}}]
  @type t :: %__MODULE__{:id => (integer()), :name => (String.t()), :active => (boolean()), :nickname => (nil | String.t()), :pets => ([Example.Protocol.UserSkir.User.Pet.t() | :skir_default]), :address => (Example.Protocol.CommonSkir.Address.t() | :skir_default), :avatar => (binary()), :created_at => (integer()), :status => (Example.Protocol.UserSkir.Event.t()), :__skir_unknown_fields__ => map()}
  @spec new(map() | keyword()) :: t()
  def new(attrs \\ %{}), do: struct!(__MODULE__, attrs)
  @spec default() :: t()
  def default(), do: %__MODULE__{}
  @doc false
  def schema() do
    %{kind: :struct, module: __MODULE__, key: "user.skir:User", doc: "",
      slots: 10, removed: [1],
      fields: [%{name: :id, json_name: "id", number: 0, doc: "", type: :int64, key_path: []},
        %{name: :name, json_name: "name", number: 2, doc: "", type: :string, key_path: []},
        %{name: :active, json_name: "active", number: 3, doc: "", type: :bool, key_path: []},
        %{name: :nickname, json_name: "nickname", number: 4, doc: "", type: {:optional, :string}, key_path: []},
        %{name: :pets, json_name: "pets", number: 5, doc: "", type: {:array, {:record, Example.Protocol.UserSkir.User.Pet}}, key_path: []},
        %{name: :address, json_name: "address", number: 6, doc: "", type: {:record, Example.Protocol.CommonSkir.Address}, key_path: []},
        %{name: :avatar, json_name: "avatar", number: 7, doc: "", type: :bytes, key_path: []},
        %{name: :created_at, json_name: "created_at", number: 8, doc: "", type: :timestamp, key_path: []},
        %{name: :status, json_name: "status", number: 9, doc: "", type: {:record, Example.Protocol.UserSkir.Event}, key_path: []}]}
  end
  @spec type() :: Skir.type()
  def type(), do: {:record, __MODULE__}
  @spec to_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def to_json(value, opts \\ []), do: Skir.to_json(type(), value, opts)
  @spec to_json!(term(), keyword()) :: term()
  def to_json!(value, opts \\ []), do: Skir.to_json!(type(), value, opts)
  @spec from_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def from_json(value, opts \\ []), do: Skir.from_json(type(), value, opts)
  @spec from_json!(term(), keyword()) :: term()
  def from_json!(value, opts \\ []), do: Skir.from_json!(type(), value, opts)
  @spec encode_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def encode_json(value, opts \\ []), do: Skir.encode_json(type(), value, opts)
  @spec encode_json!(term(), keyword()) :: binary()
  def encode_json!(value, opts \\ []), do: Skir.encode_json!(type(), value, opts)
  @spec decode_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def decode_json(value, opts \\ []), do: Skir.decode_json(type(), value, opts)
  @spec decode_json!(term(), keyword()) :: term()
  def decode_json!(value, opts \\ []), do: Skir.decode_json!(type(), value, opts)
  @spec encode(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def encode(value, opts \\ []), do: Skir.encode(type(), value, opts)
  @spec encode!(term(), keyword()) :: binary()
  def encode!(value, opts \\ []), do: Skir.encode!(type(), value, opts)
  @spec decode(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def decode(value, opts \\ []), do: Skir.decode(type(), value, opts)
  @spec decode!(term(), keyword()) :: term()
  def decode!(value, opts \\ []), do: Skir.decode!(type(), value, opts)
end

defmodule Example.Protocol.UserSkir.User.Pet do
  @moduledoc "Generated from user.skir:Pet"
  defstruct [{:name, ""}, {:picture, ""}, {:__skir_unknown_fields__, %{}}]
  @type t :: %__MODULE__{:name => (String.t()), :picture => (String.t()), :__skir_unknown_fields__ => map()}
  @spec new(map() | keyword()) :: t()
  def new(attrs \\ %{}), do: struct!(__MODULE__, attrs)
  @spec default() :: t()
  def default(), do: %__MODULE__{}
  @doc false
  def schema() do
    %{kind: :struct, module: __MODULE__, key: "user.skir:User.Pet", doc: "",
      slots: 2, removed: [],
      fields: [%{name: :name, json_name: "name", number: 0, doc: "", type: :string, key_path: []},
        %{name: :picture, json_name: "picture", number: 1, doc: "", type: :string, key_path: []}]}
  end
  @spec type() :: Skir.type()
  def type(), do: {:record, __MODULE__}
  @spec to_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def to_json(value, opts \\ []), do: Skir.to_json(type(), value, opts)
  @spec to_json!(term(), keyword()) :: term()
  def to_json!(value, opts \\ []), do: Skir.to_json!(type(), value, opts)
  @spec from_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def from_json(value, opts \\ []), do: Skir.from_json(type(), value, opts)
  @spec from_json!(term(), keyword()) :: term()
  def from_json!(value, opts \\ []), do: Skir.from_json!(type(), value, opts)
  @spec encode_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def encode_json(value, opts \\ []), do: Skir.encode_json(type(), value, opts)
  @spec encode_json!(term(), keyword()) :: binary()
  def encode_json!(value, opts \\ []), do: Skir.encode_json!(type(), value, opts)
  @spec decode_json(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def decode_json(value, opts \\ []), do: Skir.decode_json(type(), value, opts)
  @spec decode_json!(term(), keyword()) :: term()
  def decode_json!(value, opts \\ []), do: Skir.decode_json!(type(), value, opts)
  @spec encode(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def encode(value, opts \\ []), do: Skir.encode(type(), value, opts)
  @spec encode!(term(), keyword()) :: binary()
  def encode!(value, opts \\ []), do: Skir.encode!(type(), value, opts)
  @spec decode(term(), keyword()) :: {:ok, term()} | {:error, Skir.Error.t()}
  def decode(value, opts \\ []), do: Skir.decode(type(), value, opts)
  @spec decode!(term(), keyword()) :: term()
  def decode!(value, opts \\ []), do: Skir.decode!(type(), value, opts)
end

defmodule Example.Protocol.UserSkir do
  @moduledoc "Constants and method descriptors for this Skir source file."
  @doc "ALICE"
  @spec alice_const() :: Example.Protocol.UserSkir.User.t() | :skir_default
  def alice_const(), do: Skir.from_json!({:record, Example.Protocol.UserSkir.User}, [42, 0, "Alice"])
  @doc "Load one user."
  @spec get_user_method() :: Skir.Method.t()
  def get_user_method(), do: %Skir.Method{name: "GetUser", number: 12345, doc: "Load one user.", request: :int64, response: {:record, Example.Protocol.UserSkir.User}}
  @doc "Register a handler for GetUser on a Skir.RPC.Service."
  @type get_user_handler :: (integer(), term() -> {:ok, Example.Protocol.UserSkir.User.t() | :skir_default} | {:error, Skir.RPC.ServiceError.t() | Skir.RPC.UnknownError.t()})
  @spec add_get_user(Skir.RPC.Service.t(), get_user_handler()) :: Skir.RPC.Service.t()
  def add_get_user(service, handler), do: Skir.RPC.Service.add_method(service, get_user_method(), handler)
  @doc "Invoke GetUser through a Skir.RPC.ServiceClient."
  @spec get_user(Skir.RPC.ServiceClient.t(), integer(), keyword()) :: {:ok, Example.Protocol.UserSkir.User.t() | :skir_default} | {:error, Skir.RPC.RpcError.t()}
  def get_user(client, request, opts \\ []), do: Skir.RPC.ServiceClient.invoke(client, get_user_method(), request, opts)
  @doc "Invoke GetUser; raise Skir.RPC.RpcError on failure."
  @spec get_user!(Skir.RPC.ServiceClient.t(), integer(), keyword()) :: Example.Protocol.UserSkir.User.t() | :skir_default
  def get_user!(client, request, opts \\ []), do: Skir.RPC.ServiceClient.invoke!(client, get_user_method(), request, opts)
  @doc "All SkirRPC methods declared in this source file."
  @spec methods() :: [Skir.Method.t()]
  def methods(), do: [get_user_method()]
end
